Issue 2 check ownership groups
fitzgen/is_executable pull request #7
Opened 2021-06-05 03:47 UTC by dmgolembiowski

Added a feature extension to check the group and owner bits on the file in question. The feature is available for Unix OS's.

2021-06-05 03:54 UTC, dmgolembiowski commented
For #2

2021-06-05 17:55 UTC, dmgolembiowski commented
@fitzgen Would you be able to offer any guidance or suggestions on what I need to do to make this pass? This is my first open source PR, so I'm a little lost.

2021-11-01 20:58 UTC, alpha-tango-kilo requested changes
Hey @dmgolembiowski - I'm not a maintainer or the owner of this repo but I stumbled across your PR and thought it deserved a look at since you're trying to give back to the community!

Other general notes that don't really fit anywhere:
* Your commit history is messing. Look into using "git interactive rebase" if you're unfamiliar with it and squash your work down into small, atomic commits, that each work by themselves. In my PR (#6), I made one commit for the functionality change, another to add the tests. Something similar would probably make sense here. You'll need to force push your branch to amend things in this PR
* If you use the phrase "Will close" in your original PR message followed by the issue number, GitHub will automagically identify that your PR will close an issue if it's merged, saved the owner or a maintainer having to do that manually

Please note I'm running Windows so I'm not actually able to test your additions, just can help you make your code compile, pass tests, and get this PR tidy ready for reviewing to be merged :)

2021-11-01 20:58 UTC, alpha-tango-kilo commented on Cargo.toml
> +[dependencies]
This dependency should be Unix only, see [this section](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) of the Cargo book for a how to
```suggestion
[target.'cfg(unix)'.dependencies]
```

2021-11-01 20:58 UTC, alpha-tango-kilo commented on src/lib.rs
> +pub fn is_permitted<P>(path: P) -> Result<::std::path::PathBuf, io::Error>
Use the full path for `io` here and get rid of the import on line 58, it's unneeded unless compiling for Unix

2021-11-01 20:58 UTC, alpha-tango-kilo commented on src/lib.rs
> +
Adding random whitespace isn't good practice for creating a PR. You don't want to change anything more than necessary

2021-11-01 20:58 UTC, alpha-tango-kilo commented on src/lib.rs
> +    impl IsPermitted for Path {
The formatting within this `impl` is questionable. I'd recommend trying to use `rustfmt` if you can do without massively changing other parts of the lib, or tidying this up yourself by hand

2021-11-01 20:58 UTC, alpha-tango-kilo commented on tests/tests.rs
> +use is_executable::{ is_executable, is_permitted };
This import won't work when compiling for not-Unix. Importing `is_permitted` must be done in `mod unix`

2021-11-01 20:58 UTC, alpha-tango-kilo commented on src/lib.rs
> +pub trait IsPermitted {
Both this trait declaration and `is_permitted` might as well go into the `mod unix`, You may need to add a `pub use` statement to re-export what's needed to the base of the crate if that's what you're after

2022-03-17 19:47 UTC, closed without merging